replicaCount: 2

image:
  tag: v0.12.9

ingress:
  host: chat.jcrlabs.net
  apiBackend:
    service: chat-back
    port: 80
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$remote_addr"

hpa:
  minReplicas: 2
  maxReplicas: 5
